### ISSUE TITLE
Varsel i chat

### ISSUE THREAD

**Issue by EmtyCrax** [Uraxys/SkyLands-Info#18]
kan dere fikse som pluggin som fikser sånn at når det er noen som skriver navnet ditt i chat så kommer man eit pling.

+1 for upvote
-1 for unvote

**Comment by Fowy** [comment]
This is a feature on LabyMod as well...

**Comment by EmtyCrax** [comment]
i do not use labymod

**Comment by Uraxys** [comment]
Won't do it as you can use mods to get the same effect, also, just read the chat.
