### ISSUE TITLE
Fly på survival

### ISSUE THREAD

**Issue by EmtyCrax** [Uraxys/SkyLands-Info#9]
hei, jeg mener att fly på survival er veldig greit og hatt. men ikke hvis vi hadde brukt det til en annen fordel enn moderering. (eit eksempel på hvordan du bruker den)

Hvis mod's vil ha tilgang til den kan de som er Moderator rank og ikke de som er Ny Moderator rank få tilgang. slik at, folk ikke søker bare for også få tilgang til /fly

Du ser en fyr som er misstekelig. men vil ikke gå i /gmsp fordi du ikke vil bli teleportet til spawn igjen. kanskje du vil skjekke ut en annen spiller som er veldig nær. men da kan man jo sikkert bare teleportere. men det kan av og til virke litt stressende og sånne ting.

**Comment by Fowy** [comment]
No.

**Comment by StickingPinning** [comment]
-1 

-Noahgb01
